CREATE DATABASE HR

use HR

CREATE TABLE regions (
    REGION_ID INT PRIMARY KEY,
    REGION_NAME VARCHAR(25) NOT NULL
);

CREATE TABLE countries (
    COUNTRY_ID CHAR(2) PRIMARY KEY,
    COUNTRY_NAME VARCHAR(40) NOT NULL,
    REGION_ID INT NOT NULL,
    FOREIGN KEY (REGION_ID) REFERENCES regions(REGION_ID)
);

CREATE TABLE locations (
    LOCATION_ID INT PRIMARY KEY,
    STREET_ADDRESS VARCHAR(25),
    POSTAL_CODE VARCHAR(12),
    CITY VARCHAR(30) NOT NULL,
    STATE_PROVINCE VARCHAR(12),
    COUNTRY_ID CHAR(2) NOT NULL,
    FOREIGN KEY (COUNTRY_ID) REFERENCES countries(COUNTRY_ID)
);

CREATE TABLE departments (
    DEPARTMENT_ID INT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(30) NOT NULL,
    MANAGER_ID INT,
    LOCATION_ID INT NOT NULL,
    FOREIGN KEY (LOCATION_ID) REFERENCES locations(LOCATION_ID)
);

CREATE TABLE jobs (
    JOB_ID VARCHAR(10) PRIMARY KEY,
    JOB_TITLE VARCHAR(35) NOT NULL,
    MIN_SALARY INT,
    MAX_SALARY INT
);

CREATE TABLE employees (
    EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(25) NOT NULL,
    EMAIL VARCHAR(20) NOT NULL UNIQUE,
    PHONE_NUMBER VARCHAR(20),
    HIRE_DATE DATE NOT NULL,
    JOB_ID VARCHAR(10) NOT NULL,
    SALARY INT,
    COMMISSION_PCT DECIMAL(5, 2),
    MANAGER_ID INT,
    DEPARTMENT_ID INT,
    FOREIGN KEY (JOB_ID) REFERENCES jobs(JOB_ID),
    FOREIGN KEY (MANAGER_ID) REFERENCES employees(EMPLOYEE_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES departments(DEPARTMENT_ID)
);

CREATE TABLE job_history (
    EMPLOYEE_ID INT,
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    JOB_ID VARCHAR(10) NOT NULL,
    DEPARTMENT_ID INT NOT NULL,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES employees(EMPLOYEE_ID),
    FOREIGN KEY (JOB_ID) REFERENCES jobs(JOB_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES departments(DEPARTMENT_ID),
    PRIMARY KEY (EMPLOYEE_ID, START_DATE)
);

CREATE TABLE job_grades (
    GRADE_LEVEL VARCHAR(2) PRIMARY KEY,
    LOWEST_SAL INT NOT NULL,
    HIGHEST_SAL INT NOT NULL
);
